# Generated by Django 5.1.4 on 2025-02-12 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporation",
            name="hr_team_members",
            field=models.ManyToManyField(
                blank=True, related_name="hr_team_members", to="person.person"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="member_of_teams", to="person.person"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leading_teams",
                to="person.person",
            ),
        ),
    ]
