# Generated by Django 5.1.4 on 2025-02-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_corporation_hr_team_members_team_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="parent_teams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="lower_teams", to="company.team"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="sub_teams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="super_teams", to="company.team"
            ),
        ),
    ]
