# Generated by Django 5.1.4 on 2025-02-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_team_parent_teams_alter_team_sub_teams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporation",
            name="hr_team_members",
        ),
        migrations.AddField(
            model_name="corporation",
            name="hr_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corporation_hr_team",
                to="company.team",
            ),
        ),
    ]
